version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
      - . "$READTHEDOCS_VIRTUALENV_PATH/bin/activate" && poetry install --with docs
      - pip freeze

sphinx:
  configuration: docs/conf.py
